#!/bin/bash

source /home/bob/pbuilder/targets

echo "targets: $TARGETS"

echo "# with dput for uploading.

[DEFAULT]
login = username
method = ftp
hash = md5
allow_unsigned_uploads = 0
run_lintian = 0
run_dinstall = 0
check_version = 0
scp_compress = 0
post_upload_command =
pre_upload_command =
passive_ftp = 1
default_host_main = SIL
default_host_non-us = SIL

[PALASO]
method = scp
fqdn = packages.palaso.org
incoming = /var/lib/debarchiver/incoming
login = packager
"

for TARGET in $TARGETS; do

echo "[PALASO-${TARGET}]
method = scp
fqdn = packages.palaso.org
incoming = /var/lib/debarchiver/incoming/${TARGET}
login = packager
"
done
