#! /bin/bash

# Cron sript

PBDIR=/home/bob/pbuilder

[ -x $PBDIR/updatepbuilder.sh ] || exit 0
[ -r $PBDIR/targets ] || exit 0
[ -e $PBDIR/targets.old ] || cp $PBDIR/targets $PBDIR/targets.old
[ -w $PBDIR/targets.old ] || exit 0
[ ! -f $PBDIR/updatingpbuilder ] || exit 0

touch $PBDIR/updatingpbuilder

date
cd $PBDIR && hg pull && hg update

if ! cmp -s $PBDIR/targets $PBDIR/targets.old; then
	cd $PBDIR && ./updatepbuilder.sh > /home/bob/updatepb.log
	cd $PBDIR && ./createdputconf > /home/bob/.dput.cf
	cp $PBDIR/targets $PBDIR/targets.old
#    echo "run updatepbuilder.sh"
#else
#    echo "nothing has changed"
fi

rm $PBDIR/updatingpbuilder
